name: Build Utils
on: [workflow_call,push, pull_request, workflow_dispatch]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.0
          cache: pip
      - name: Poetry Build
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - run: pip install -r requirements.txt
      - run: cd analysis/utils && poetry build
